import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ttFirs = localFont({
  src: [
    {
      path: "../public/fonts/tt_firs_neue/TT Firs Neue Trial ExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/fonts/tt_firs_neue/TT Firs Neue Trial Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/tt_firs_neue/TT Firs Neue Trial Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/tt_firs_neue/TT Firs Neue Trial Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-tt-firs",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ttFirs.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}