# Generated by Django 5.2.1 on 2026-03-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/covers/'),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
