# Generated by Django 5.2.1 on 2026-03-30 04:30

import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_cover_image_news_seo_description_news_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
