# Generated by Django 5.2.1 on 2026-03-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField()),
                ('page_type', models.CharField(choices=[('about', 'About'), ('contacts', 'Contacts'), ('mission', 'Mission'), ('management', 'Management'), ('compliance', 'Compliance'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('kk', 'Kazakh'), ('en', 'English')], default='ru', max_length=2)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
