# Generated by Django 5.2.1 on 2026-03-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('about', 'About'), ('management', 'Management'), ('safety', 'Safety'), ('compliance', 'Compliance'), ('npa', 'NPA'), ('development_plan', 'Development Plan'), ('additional_info', 'Additional Info'), ('gallery', 'Gallery'), ('contacts', 'Contacts'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
