# Generated by Django 5.2.1 on 2026-03-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_options_alter_page_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('main', 'Main'), ('about', 'About'), ('news', 'News'), ('procurement', 'Procurement'), ('vacancies', 'Vacancies'), ('contacts', 'Contacts'), ('about_kaes_llp', 'About KAES LLP'), ('types_of_activities', 'Types of Activities'), ('additional_info', 'Additional Info'), ('gallery', 'Gallery'), ('management', 'Management'), ('safety', 'Safety'), ('compliance', 'Compliance'), ('npa', 'NPA'), ('development_plan', 'Development Plan'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
